### ISSUE TITLE
[BUG] Can't see installed only proton verions.

### ISSUE THREAD

**Issue by ecabott** [Vysp3r/ProtonPlus#162]
![Screenshot from 2023-11-25 22-01-49](https://github.com/Vysp3r/ProtonPlus/assets/58223130/66b35e18-c698-44ad-8aa0-ad1033070475)

Just keeps spinning.

Also, I think a separate installed tab would be better than clicking every proton variants to see if there are installed versions.

**Comment by Vysp3r** [comment]
Could you make a quick drawing of what you would want the UI to look like? I can't seem to picture what you said in my head so that would help me a lot.

**Comment by ChrisLauinger77** [comment]
Installed only does also not work for me. It just shows the spinner and nothing happens.
I like the propsed idea.

**Comment by Vysp3r** [comment]
Must have messed something up in the last update for the installed only option not working. As for your idea, I will try it to see if I like it or not. I'll keep you up to date.

**Comment by Vysp3r** [comment]
![image](https://github.com/Vysp3r/ProtonPlus/assets/62019735/38b1c2b7-fb2a-4dc5-bfe4-9b7aea891304)

Here's a sneak peak :)

**Comment by ChrisLauinger77** [comment]
Awesome !

**Comment by Vysp3r** [comment]
So after working on this I came to the realization that we can't really know what's installed that way since we don't know from what runner the release is from. For Proton-GE it's easy since the name is straightforward, but for the majority of them it's not. I could of course add some separators and titles so that you know where it comes from, but that would make that part of the UI really heavy in my opinion. On top of that it would require me to A rewrite a lot of the backend so that the releases from the sidebar are the same and not a copy since otherwise there's no way for the release in the sidebar to know that it was deleted from the right part and vice-versa. The other option would be to add some timers that would check on each side if they're still installed, but that would be heavy on the system for not a lot of gains. All of that to say that I will not be following with that request since I have other projects I want to work on and don't want to spend days rewriting the backend another time.

**Comment by Vysp3r** [comment]
Forgot to say that I fixed the installed releases not loading.
